### ISSUE TITLE
verifyPassword != checkPassword

### ISSUE THREAD

**Issue by iffy** [lvh/txscrypt#1]
in txscrypt/**init**.py `checkPassword` is imported, but `__all__` contains `verifyPassword`.  Also, the README refers to `verifyPassword` which fails to import.

```
$ python -c 'from txscrypt import verifyPassword'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name verifyPassword
```

**Comment by lvh** [comment]
What? I remember fixing this! On it, thanks for reporting.

**Comment by lvh** [comment]
Would you mind code reviewing that commit and verify that it addresses the issue?

**Comment by iffy** [comment]
It doesn't fail for the import now.  Thanks!

(I'm getting _scrypt problems errors, but that's probably a function of pip and virtualenvs not working well)

**Comment by iffy** [comment]
Okay it works for sure:

``` pycon
$ python
Python 2.7.3 (default, Apr 10 2013, 06:20:15) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from txscrypt import computeKey
>>> from txscrypt import checkPassword
>>> import txscrypt
>>> txscrypt.__version__
'1.1.1'
```

**Comment by lvh** [comment]
Excellent! Thanks for the bug report (I credited you in the README), I'll
upload the shiny new version to PyPI now.
